### ISSUE TITLE
armv7 supported?

### ISSUE THREAD

**Issue by ghost** [f1shl3gs/roxy#13]
Hello, I came here from following clash for ros, and I haven't found out how your project runs on ros container. Could you give me a hint? 
In addition, since I can't afford a 5009, can he support the armv7 version of the hardware?

**Comment by f1shl3gs** [comment]
The [container](https://help.mikrotik.com/docs/display/ROS/Container) feature was added in RouterOS v7.4beta4. So, in theory, you can run any docker image on MikroTik device with ros v7.4beta4 or new version. 

As for armv7, you can build it with following command, but i'm not queit sure if it will work as expected ( i don't have any armv7 device ).

```shell
# docker and cargo-cross is required
cross build --release --target armv7-unknown-linux-musleabi
```
